# Generated by Django 5.0.3 on 2024-03-26 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("numberOfSongs", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255, unique=True)),
                ("album", models.CharField(max_length=255)),
                ("length", models.TimeField(default=datetime.time)),
                ("playlist", models.ManyToManyField(to="zing_it.playlist")),
            ],
        ),
    ]
